### ISSUE TITLE
msg.lat/lon != msg.location.lat/lon

### ISSUE THREAD

**Issue by tedstriker** [hardillb/node-red-node-geofence#1]
If you use msg.lat and msg.lon it is not possible to concatenate multiple region nodes.
A "TypeError: Cannot read property 'toString' of undefined" error is thrown.

If msg.location.lat/lon is used instead everything works fine.

**Comment by hardillb** [comment]
Can you give a bit more detail, maybe an example flow that shows the problem

**Comment by tedstriker** [comment]
Of course. I made a simple example to demonstrate the issue. 
Just import the attached flow. BTW: Why are there two ways to hand over lat & lon?

`[{"id":"eeb50a12.114af8","type":"change","z":"4c3d7239.b3c28c","name":"","rules":[{"t":"move","p":"payload.lat","pt":"msg","to":"location.lat","tot":"msg"},{"t":"move","p":"payload.lon","pt":"msg","to":"location.lon","tot":"msg"},{"t":"delete","p":"payload","pt":"msg"},{"t":"delete","p":"topic","pt":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":320,"y":240,"wires":[["7543b69c.8abc48"]]},{"id":"7543b69c.8abc48","type":"geofence","z":"4c3d7239.b3c28c","name":"Place1","mode":"circle","inside":"both","rad":86723.74421339622,"points":[],"centre":{"latitude":-24.785487759736924,"longitude":120.83518981933592},"x":510,"y":240,"wires":[["d3a26735.2c5d98"]]},{"id":"9710f3c6.68ef1","type":"debug","z":"4c3d7239.b3c28c","name":"","active":true,"console":"false","complete":"location.isat","x":770,"y":300,"wires":[]},{"id":"ec2ae6ee.13d518","type":"change","z":"4c3d7239.b3c28c","name":"","rules":[{"t":"move","p":"payload.lat","pt":"msg","to":"lat","tot":"msg"},{"t":"move","p":"payload.lon","pt":"msg","to":"lon","tot":"msg"},{"t":"delete","p":"payload","pt":"msg"},{"t":"delete","p":"topic","pt":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":320,"y":300,"wires":[["7543b69c.8abc48"]]},{"id":"b5eb4eba.4a14b","type":"inject","z":"4c3d7239.b3c28c","name":"Success","topic":"","payload":"{\"lat\": -25.475823, \"lon\":120.948486}","payloadType":"json","repeat":"","crontab":"","once":false,"x":100,"y":240,"wires":[["eeb50a12.114af8"]]},{"id":"d3a26735.2c5d98","type":"geofence","z":"4c3d7239.b3c28c","name":"Place2","mode":"circle","inside":"both","rad":44596.96607486069,"points":[],"centre":{"latitude":-25.403584973186703,"longitude":121.11328124999999},"x":510,"y":300,"wires":[["9710f3c6.68ef1"]]},{"id":"bfbfec21.40401","type":"inject","z":"4c3d7239.b3c28c","name":"Error","topic":"","payload":"{\"lat\":-26.956694, \"lon\": 127.816315}","payloadType":"json","repeat":"","crontab":"","once":false,"x":90,"y":300,"wires":[["ec2ae6ee.13d518"]]}]`

**Comment by hardillb** [comment]
Thanks for that, it shows the problem. This is a strange one because the error doesn't look to be coming from any of the node's code.

I'll keep poking at it.

There are support for multiple input formats to handle a bunch of legacy data sources that the node was originally written to deal with.

**Comment by hardillb** [comment]
Not sure why the error was showing up where it was, but I've fixed it.

0.0.15 should be in npm now
