### ISSUE TITLE
Geofence not complete on latest Node-Red

### ISSUE THREAD

**Issue by scargill** [hardillb/node-red-node-geofence#12]
In my new NR installation, Raspberry Pi 3, up to node nodejs (10.1) and latest NR, Geofence installs but no sign of the controls for thw fence area like rectangle or cirsle - any ideas? All other nodes seem fine,.

**Comment by hardillb** [comment]
Have you installed to broken fork?

**Comment by scargill** [comment]
Alright - ignore me - must've been the later contrib version. On removing and re-installing I now have the rectangle etc controls. Love it.
