### ISSUE TITLE
Load tiles over https

### ISSUE THREAD

**Issue by oliv3** [hardillb/node-red-node-geofence#15]
Hi, this node loads tiles over http, so they are blocked when using a content security policy:

`Content Security Policy: The page’s settings blocked the loading of a resource at http://a.tile.openstreetmap.org/8/126/84.png (“img-src”).`

Would it be possible to load them over https (as done in the worldmap node) ? Thanks !

**Comment by hardillb** [comment]
Version 0.1.2 pushed to npm

**Comment by oliv3** [comment]
Woaw that was fast :) Thanks !
