### ISSUE TITLE
Flow not working - nothing happens

### ISSUE THREAD

**Issue by MTrab** [hardillb/node-red-node-geofence#16]
Can one of you see what's wrong with this flow?

`[{"id":"19f5dd13.e948d3","type":"geofence","z":"19e6954.3f28a6b","name":"Home Zone","mode":"circle","inside":"true","rad":125.86661890884864,"points":[],"centre":{"latitude":55.99535753046051,"longitude":9.880538173019884},"x":670,"y":820,"wires":[["9bd62501.fd7568"]]},{"id":"f63a2252.d8746","type":"api-current-state","z":"19e6954.3f28a6b","name":"Get Person Entity","server":"76ca0172.30ea9","version":1,"outputs":1,"halt_if":"","halt_if_type":"str","halt_if_compare":"is","override_topic":false,"entity_id":"person.morten","state_type":"str","state_location":"payload","override_payload":"msg","entity_location":"data","override_data":"msg","blockInputOverrides":false,"x":270,"y":820,"wires":[["f1d05d9c.066a7"]]},{"id":"9cf75a81.721938","type":"inject","z":"19e6954.3f28a6b","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":100,"y":820,"wires":[["f63a2252.d8746"]]},{"id":"9bd62501.fd7568","type":"debug","z":"19e6954.3f28a6b","name":"Output","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":830,"y":780,"wires":[]},{"id":"f1d05d9c.066a7","type":"function","z":"19e6954.3f28a6b","name":"Get and format attribs","func":"var lat = msg.data.attributes.latitude;\nvar lon = msg.data.attributes.longitude;\nvar state = msg.data.state;\n\nvar newMsg = {\n    \"location\":\n    {\n        \"lat\": lat,\n        \"lon\": lon\n        \n    }\n};\n\nreturn newMsg;","outputs":1,"noerr":0,"x":480,"y":820,"wires":[["19f5dd13.e948d3","9bd62501.fd7568"]]},{"id":"76ca0172.30ea9","type":"server","z":"","name":"Home Assistant","legacy":false,"hassio":true,"rejectUnauthorizedCerts":true}]`

Example output is:

`{"location":{"lat":56.0502095,"lon":9.9631012},"_msgid":"9d10c114.ecb1d"}`

**Comment by hardillb** [comment]
No, because you've not included anywhere near enough information to be able to help.

You've not described the expected output or what you are actually getting.

**Comment by MTrab** [comment]
Yes I have:

Example output is:

{"location":{"lat":56.0502095,"lon":9.9631012},"_msgid":"9d10c114.ecb1d"}

I get no output from the geofence node.

**Comment by hardillb** [comment]
Also you have some random node in the flow that I have no idea what it is (api-current-state), If you want help strip the test case down to just an inject node, geofence and debug node.

**Comment by MTrab** [comment]
It's getting a entity state from Home Assistant, where I have my current location present in a device tracker.

**Comment by hardillb** [comment]
Having fixed your test flow:

[{"id":"8a6175da.9b0468","type":"geofence","z":"ebdeabed.e4aea8","name":"Home Zone","mode":"circle","inside":"true","rad":125.86661890884864,"points":[],"centre":{"latitude":55.99535753046051,"longitude":9.880538173019884},"x":550,"y":180,"wires":[["3c55cfc4.a8366"]]},{"id":"36a4e0b0.569fc","type":"inject","z":"ebdeabed.e4aea8","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":120,"y":160,"wires":[["d51801e9.d01a6"]]},{"id":"3c55cfc4.a8366","type":"debug","z":"ebdeabed.e4aea8","name":"Output","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":770,"y":180,"wires":[]},{"id":"d51801e9.d01a6","type":"function","z":"ebdeabed.e4aea8","name":"","func":"\nmsg.location = {\n    \"lat\":56.0502095,\n    \"lon\":9.9631012\n};\n\nreturn msg;","outputs":1,"noerr":0,"x":310,"y":160,"wires":[["8a6175da.9b0468"]]}]

This is working as it should. The input point is outside the circle so it is getting filtered out.

Check which node you have installed. The correct node is `node-red-node-geofence` NOT `node-red-contrib-geofence`

**Comment by MTrab** [comment]
`[{"id":"71459464.30b5cc","type":"inject","z":"19e6954.3f28a6b","name":"","topic":"","payload":"{\"lat\":56.0502095,\"lon\":9.9631012}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":150,"y":960,"wires":[["ae61af6f.b0ebf"]]},{"id":"ae61af6f.b0ebf","type":"geofence","z":"19e6954.3f28a6b","name":"Home Zone","mode":"circle","inside":"true","rad":125.86661890884864,"points":[],"centre":{"latitude":55.99535753046051,"longitude":9.880538173019884},"x":290,"y":960,"wires":[["6967576d.1ca058"]]},{"id":"6967576d.1ca058","type":"debug","z":"19e6954.3f28a6b","name":"Output","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":430,"y":960,"wires":[]}]`

Still no output from the geofence node.

**Comment by MTrab** [comment]
> [{"id":"8a6175da.9b0468","type":"geofence","z":"ebdeabed.e4aea8","name":"Home Zone","mode":"circle","inside":"true","rad":125.86661890884864,"points":[],"centre":{"latitude":55.99535753046051,"longitude":9.880538173019884},"x":550,"y":180,"wires":[["3c55cfc4.a8366"]]},{"id":"36a4e0b0.569fc","type":"inject","z":"ebdeabed.e4aea8","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":120,"y":160,"wires":[["d51801e9.d01a6"]]},{"id":"3c55cfc4.a8366","type":"debug","z":"ebdeabed.e4aea8","name":"Output","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":770,"y":180,"wires":[]},{"id":"d51801e9.d01a6","type":"function","z":"ebdeabed.e4aea8","name":"","func":"\nmsg.location = {\n "lat":56.0502095,\n "lon":9.9631012\n};\n\nreturn msg;","outputs":1,"noerr":0,"x":310,"y":160,"wires":[["8a6175da.9b0468"]]}]

For some reason I can't import this. Syntax error.

**Comment by hardillb** [comment]
You've probably included extra new line characters when copy/pasting.

But as I've already said, the input point is outside the circle so the node is doing the right thing.
