### ISSUE TITLE
Not usable on rural properties - possibility of open sat images?

### ISSUE THREAD

**Issue by bitwombat** [hardillb/node-red-node-geofence#17]
Thanks for this cool flow! Unfortunately, I'm on a rural property, so I just see a big tan block when I go to set my shapes. I need satellite images. 

Google Maps requires accounts and API keys these days... so not sure how node-red-node-geofence could provide satellite images.

Any plans to incorporate sat images somehow, someday?

**Comment by hardillb** [comment]
This node doens't use Google maps it uses OpenStreetmap.

If you can find a free open satellite tile source that will work with leaflet.js then feel free to submit a pull request to add it.

The other option is to disable the map (rename geofence.html to something else and then rename geofence-nomap.html to geofence.html) which will let you enter the centre point lat, long and radius manually (this code has not been tested in a LONG time).

Other than that all I can suggest is you contribute to OpenStreetMap (https://wiki.openstreetmap.org/wiki/How_to_contribute) to add more data for your area.
