### ISSUE TITLE
Manual entry of points

### ISSUE THREAD

**Issue by nelsonblaha** [hardillb/node-red-node-geofence#18]
I need to pick out my points in a satellite photo. Is there a way to get at the manual points and define them by lat/long instead of using the handy OSM interface?

**Comment by hardillb** [comment]
If you look in the node-red-node-geofence directory in `~/.node-red/node_modules` you should find `geofence-nomap.html`.

if you rename `geofence.html` to something else and then rename `geofence-nomap.html` to `geofence.html` you should get a version of the config window without the map.

I've not used/tested this interface in a LONG time so use at your own risk.
