### ISSUE TITLE
Unable to type in search feature

### ISSUE THREAD

**Issue by majerus1223** [hardillb/node-red-node-geofence#19]
When you try to type in the search box for a location, you are unable to do so. I have tried from firefox, chrome and new build of edge. If there is something I can provide to help troubleshoot this please let me know. Thanks!

![image](https://user-images.githubusercontent.com/7389171/96529329-7e40fc00-124a-11eb-9b3a-487e0985ef05.png)

**Comment by majerus1223** [comment]
Tried to copy and paste a location in, no luck.

![image](https://user-images.githubusercontent.com/7389171/96529524-04f5d900-124b-11eb-986a-43abc235548e.png)

**Comment by hardillb** [comment]
You need to supply versions for everything (node-red, the node, nodejs)

Also open the browser console (before opening the conf editor) and supply details of any errors shows.

**Comment by majerus1223** [comment]
Node Red - v1.1.2
nodejs - 10.21.0
node - 0.1.2 

Normal Loading
![image](https://user-images.githubusercontent.com/7389171/96593349-03f69300-12af-11eb-8bc1-38d6d2bd977e.png)


Open dev tools, then navigate to the page.
![image](https://user-images.githubusercontent.com/7389171/96593233-e0cbe380-12ae-11eb-9162-86881a7da5d9.png)

**Comment by hardillb** [comment]
OK, I think I know what the problem is.

Can you test by deleting the `class="form-row"` from line 10 in geofence.html (should be in `~/.node-red/node_modules/node-red-node-geofence`)

You will have to restart Node-RED after editing this file

**Comment by majerus1223** [comment]
Removed the entire div as mentioned.. Looks like it works now :) 


![image](https://user-images.githubusercontent.com/7389171/96664797-2de49f80-1319-11eb-94fb-0d70c845a250.png)

**Comment by hardillb** [comment]
Ok I'll push a new version tonight

**Comment by hardillb** [comment]
version 0.1.3 should be on npm now

**Comment by majerus1223** [comment]
Thanks for the quick help!
