### ISSUE TITLE
node not matching points inside fence

### ISSUE THREAD

**Issue by blalor** [hardillb/node-red-node-geofence#23]
The following flow works *intermittently*; seems like it'll stop emitting messages randomly, and then never start again.  I'm using node-red v1.3.5 and node-red-node-geofence 0.2.2 installed via the "manage palette".

```
[{"id":"ddf6d68b.f189b","type":"tab","label":"Flow 2","disabled":false,"info":""},{"id":"bd8c4ec8.24092","type":"inject","z":"ddf6d68b.f189b","name":"","props":[{"p":"payload"},{"p":"timestamp","v":"$toMillis($now())/1000\t","vt":"jsonata"},{"p":"source","v":"dump1090","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"{\"hex\":\"a6a425\",\"flight\":\"NKS930  \",\"alt_baro\":1500,\"alt_geom\":1675,\"gs\":169.8,\"baro_rate\":-1280,\"category\":\"A3\",\"nav_qnh\":1019.2,\"nav_altitude_mcp\":1696,\"nav_heading\":87.2,\"lat\":37.57395400685966,\"lon\":-77.48991018535888,\"nic\":8,\"rc\":186,\"seen_pos\":11.3,\"version\":2,\"nic_baro\":1,\"nac_p\":10,\"nac_v\":4,\"sil\":3,\"sil_type\":\"perhour\",\"gva\":2,\"sda\":2,\"mlat\":[],\"tisb\":[],\"messages\":1034,\"seen\":4.2,\"rssi\":-12.4,\"name\":\"a6a425 NKS930  \",\"heading\":145.6,\"bearing\":145.6,\"icon\":\"plane\",\"layer\":\"ADSB\",\"alt\":510.54,\"label\":\"NKS930   510.54\",\"speed\":169.8,\"action\":\"send\"}","payloadType":"json","x":190,"y":200,"wires":[["1a46e819.724318"]]},{"id":"1a46e819.724318","type":"geofence","z":"ddf6d68b.f189b","name":"geofence","mode":"circle","inside":"both","rad":3400.937991358044,"points":[],"centre":{"latitude":37.57395400685966,"longitude":-77.48991018535888},"floor":"0","ceiling":"1000","worldmap":true,"outputs":2,"x":400,"y":240,"wires":[["bf4da33b.08a54"],["bf4da33b.08a54"]]},{"id":"bf4da33b.08a54","type":"debug","z":"ddf6d68b.f189b","name":"filtered","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":590,"y":300,"wires":[]}]
```

The inject node has `payload.lat` and `payload.lon` set to the center of the circle configured in the geofence node. When I activate the inject node, only the worldmap shape is emitted.

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/109915/124742460-c001f780-deea-11eb-8f5d-fea41a279192.png">

I don't see anything in the node-red log.

**Comment by hardillb** [comment]
This is because you have `msg.payload.action` set to `send` which is the trigger to send the worldmap output (and nothing else)

If you remove that field it will filter the incoming messages properly.

To be clear you are only supposed to trigger the world map updates when a new browser opens the worldmap, not on every location message

**Comment by blalor** [comment]
> To be clear you are only supposed to trigger the world map updates when a new browser opens the worldmap, not on every location message

Ah, that wasn't clear to me. It's also not clear that `action: send` is mutually exclusive with emitting the filtered messages.  Would it be possible to update the documentation to reflect those?
