### ISSUE TITLE
Inconsistent Node Behavior Related to Zone Shape

### ISSUE THREAD

**Issue by teamRibcage** [hardillb/node-red-node-geofence#25]
It seems that when the geofence zone is configured as a **circle**, the node behaves as expected. Messages are passed on when the coordinates contained in the message are within the circle, and "only points inside" is set. (setting the function to "only points outside" using the same coordinates also exhibits the expected behavior). The "inarea" property setting functions correctly as well.

`[{"id":"9b30fa1f4d34caa1","type":"inject","z":"4bc28335.d152dc","name":"","props":[{"p":"location.lat","v":"42.346584","vt":"str"},{"p":"location.lon","v":" -71.097329","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":250,"y":600,"wires":[["880e29904186e6f0"]]},{"id":"880e29904186e6f0","type":"geofence","z":"4bc28335.d152dc","name":"","mode":"circle","inside":"true","rad":162.5368718443583,"points":[],"centre":{"latitude":42.346667446208684,"longitude":-431.09723120927805},"floor":"","ceiling":"","worldmap":false,"outputs":1,"x":440,"y":600,"wires":[["986a37c019d49fa2"]]},{"id":"986a37c019d49fa2","type":"debug","z":"4bc28335.d152dc","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":620,"y":600,"wires":[]}]`

If the zone is configured as a **rectangle** or **polygon** however, the behavior of the node appears to operate in the opposite fashion. Messages are passed on if the coordinates are _outside_ the zone when "only points inside" is set. The same opposite behavior is true if "only points outside" is set (i.e. messages inside the zone are passed on). With zones of these shapes configured, the "inarea" property also appears to **always** pass a value of "false".

`[{"id":"9b30fa1f4d34caa1","type":"inject","z":"4bc28335.d152dc","name":"","props":[{"p":"location.lat","v":"42.346584","vt":"str"},{"p":"location.lon","v":" -71.097329","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":250,"y":600,"wires":[["880e29904186e6f0"]]},{"id":"880e29904186e6f0","type":"geofence","z":"4bc28335.d152dc","name":"","mode":"polyline","inside":"true","rad":0,"points":[{"latitude":42.34520919486149,"longitude":-431.09972298145294},{"latitude":42.347857652476705,"longitude":-431.09972298145294},{"latitude":42.347857652476705,"longitude":-431.0947233438492},{"latitude":42.34520919486149,"longitude":-431.0947233438492}],"centre":{},"floor":"","ceiling":"","worldmap":false,"outputs":1,"x":440,"y":600,"wires":[["986a37c019d49fa2"]]},{"id":"986a37c019d49fa2","type":"debug","z":"4bc28335.d152dc","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":620,"y":600,"wires":[]}]`

Node-Red v2.0.6 // node-red-node-geofence v0.3.0

**Comment by hardillb** [comment]
This looks to be an upstream bug in leaflet or leaflet.draw as the bounding box for your square is coming out as:

```
[
  { latitude: 42.345303508335576, longitude: -431.0995661560446 },
  { latitude: 42.34785680988681, longitude: -431.0995661560446 },
  { latitude: 42.34785680988681, longitude: -431.09467380680144 },
  { latitude: 42.345303508335576, longitude: -431.09467380680144 }
]
```

I have a nasty hack fix, but it needs digging deeper to work out what's up with the upstream components

**Comment by hardillb** [comment]
0.3.1 published with workaround.

**Comment by teamRibcage** [comment]
Thanks for the quick response and fix!
