### ISSUE TITLE
Dynamic Fence

### ISSUE THREAD

**Issue by sitan** [hardillb/node-red-node-geofence#27]
Hi, 
I'm using Home Assistant - with node-red  - with a GPS in a Minivan/Bus. 

I would like to be able set the fence dynamically. So, when we stop riding and arm the alarm, I would like to use an input of this node to set a perimeter around the current location.

I thought adding an extra check on the input message would suffice:

`if (n.worldmap && msg.hasOwnProperty("payload") && msg.payload.hasOwnProperty("dynamicfence")) {
                //override node.mode
                node.mode = 'circle';
                //set the node.centre to fence.centre
                node.centre.latitude  = msg.payload.dynamicfence.lat
                node.centre.longitude = msg.payload.dynamicfence.long
                node.centre.radius    = msg.payload.dynamicfence.radius
            }`
Is it possible to add this? ( I tried it, but could not import the adjusted node, due to a "Module not found"- error.
With kind regards, Sitan van Sluis

**Comment by hardillb** [comment]
Hi,

If you submit a Pull Request I'll have a look at it, but it will more than just this. It will also need to cover the following:

- Not just circular regions
- As a rule nodes that allow updates should not have any default values set, the node is not setup for this.
- Error checking for badly formed input messages.

**Comment by sitan** [comment]
Hi, 
thanks for your reply. When reading your (valid) comments I am of the impression that I have to create an alternate version, without default settings / form input. I'll first search for another way to accomplish this. 
Thanks!

**Comment by tazzytazzy** [comment]
I've no idea how to edit your node to complete this request, but i would also love this feature for our RV.

Perhaps, start small and just implement circles for dynamic fences.

I want to be able to park the RV and then get notified if it moves. Already have all the inputs and this nodes output with this feature would be a perfect drop in. ;)
