### ISSUE TITLE
"No location found in message"

### ISSUE THREAD

**Issue by bdydrp** [hardillb/node-red-node-geofence#28]
I seem to be getting this error in my debug panel
"No location found in message"
But the flow still works correctly

**Comment by hardillb** [comment]
I'm sorry but without a LOT more information I really can't help here.

A sample input message would be at least a start.
Along with FULL details of how the node is configured

**Comment by bdydrp** [comment]
Sorry - Just doing some testing and i get the message when i connect/disconnect from my wifi
my flow:
![image](https://user-images.githubusercontent.com/63593828/156569806-624295f6-3e05-4ad8-b220-3fbe7d6ce93a.png)
initial mqtt node is from a cloudmqtt, checks home/away, sends mqqt (local broker)
flow continues to work, even tho i get that error
I can post raw flow if needed?

**Comment by hardillb** [comment]
That still doesn't help. As I said I need to see the full make up of the input message and how you have configured the node.

**Comment by bdydrp** [comment]
![OT](https://user-images.githubusercontent.com/63593828/156571642-c96d901b-24d6-4783-b0f2-96d71885b2e3.png)
Geofence node, has polygon area slected, and action is: add "inarea" property

**Comment by hardillb** [comment]
That's no use, copy and paste the actual JSON not an image.

The debug node will put it in the clipboard if you click on the little icon on the right that appears when you mouse over the "object" in the debug sidebar.

Make sure the debug node is set to "complete message" mode

**Comment by bdydrp** [comment]
```
{
  "topic":"owntracks/Adam",
  "payload": {
     "_type":"location",
      "acc":20,
      "alt":69,
      "batt":0,
      "created_at":1646312974,
      "inregions":["Home"],
       "lat":-xx.7795243,
      "lon":xx.7526567,
      "t":"u",
      "tid":"AP",
      "tst":1646312791,
      "vac":1,
      "vel":1,
      "name":"AP"
  },
  "qos":0,
  "retain":false,"
  _msgid":"10bb440a8847d211",
  "location":{
     "lat":-xx.7795243,
     "lon":xx.7526567,
     "name":"AP",
     "inarea":true
  }
}
```

only removed actual lat/lon

**Comment by hardillb** [comment]
Exactly where in the flow did you attach the debug node?

**Comment by bdydrp** [comment]
straight after the geofence node

**Comment by hardillb** [comment]
Because that looks like after the geofence node, which is not what I asked for, I asked for the **input**, so it needs to be attached to the output of the Owntracks node

**Comment by bdydrp** [comment]
`{"topic":"owntracks/Adam","payload":{"_type":"lwt","tst":1646313872},"qos":0,"retain":false,"_msgid":"3c3e7ba8e8cfd6f9"}`

**Comment by hardillb** [comment]
Right, that message obviously doesn't have any location data in it, so the node is doing the right thing.

**Comment by bdydrp** [comment]
If thats normal - thats fine - I just found it odd, it only happens when connecting/disconnecting from wifi
Should it not happen every time owntracks sends update?

To prevent message, how do you get OT to send location? lat/long is configured in OT app config management?

**Comment by hardillb** [comment]
That's a question for Owntracks. I suggest you read the docs about what messages the Owntracks node will produce under what circumstances, but none of this is problem with the geofence node.

**Comment by bdydrp** [comment]
ok - Thanks
issue closed!
