### ISSUE TITLE
location.isat

### ISSUE THREAD

**Issue by garywilson4** [hardillb/node-red-node-geofence#6]
having chained a few geofence nodes together I'm getting an error SyntaxError: Unexpected token u in JSON at position 0 when I'm not within any of the geofence areas. This is because geofence returns an empty isat object could it be made to send something like "AWAY" rather than nothing?

**Comment by hardillb** [comment]
No,

You just need to either test the length of the array before trying to use it or wrap the access to the first element in the array in a try catch block to catch the error when there is no first element.

Also please use the Node-RED Slack or Google Group mailing list for general usage question, issues are for actual defects in the code
