### ISSUE TITLE
Dynamic fences

### ISSUE THREAD

**Issue by rjbaat** [hardillb/node-red-node-geofence#7]
Hi,
Is it possible to load dynamic geofences from a database for example?
Maybe like creating a global variable array for example?
This way the geofence list can be updated without having to stop the flow.

**Comment by hardillb** [comment]
Not currently. Pull requests may be considered

**Comment by RogierQ** [comment]
Is this still impossible?
Would like the possibility for a project

**Comment by hardillb** [comment]
Previous comment still stands, with heavy emphasis on "may"

**Comment by RogierQ** [comment]
Don't know how to do a pull request so its a no then ;-) thanks!
