### ISSUE TITLE
Cannot get square or polygons to work

### ISSUE THREAD

**Issue by shaddow825** [hardillb/node-red-node-geofence#9]
If I use a square or polygon shape, the coordinates are always returned as false. Circle over the same area works just fine. Any idea how to see what's going on?

**Comment by hardillb** [comment]
Works just fine here.

[{"id":"ed9046b5.2b1cd8","type":"geofence","z":"3f8824be.265114","name":"","mode":"polyline","inside":"true","rad":0,"points":[{"latitude":50.96426114826002,"longitude":-1.3686604489339516},{"latitude":50.96974756901714,"longitude":-1.3686604489339516},{"latitude":50.96974756901714,"longitude":-1.356987475301139},{"latitude":50.96426114826002,"longitude":-1.356987475301139}],"centre":{},"x":520,"y":160,"wires":[["6599a4f8.9d7c74"]]},{"id":"b318af9e.d0888","type":"function","z":"3f8824be.265114","name":"","func":"//50.9674878,-1.3621705\nmsg.location = {};\nmsg.location.lat = 50.9674878;\nmsg.location.lon = -1.3621705;\nreturn msg;","outputs":1,"noerr":0,"x":310,"y":220,"wires":[["ed9046b5.2b1cd8","2d352799.016928","6e027ecc.6e8cb"]]},{"id":"e1197d7.318be","type":"inject","z":"3f8824be.265114","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":160,"y":220,"wires":[["b318af9e.d0888"]]},{"id":"6599a4f8.9d7c74","type":"debug","z":"3f8824be.265114","name":"","active":true,"console":"false","complete":"true","x":750,"y":200,"wires":[]},{"id":"2d352799.016928","type":"geofence","z":"3f8824be.265114","name":"","mode":"circle","inside":"true","rad":385.26742587217336,"points":[],"centre":{"latitude":50.96783280054161,"longitude":-1.3633346557617188},"x":520,"y":200,"wires":[["6599a4f8.9d7c74"]]},{"id":"6e027ecc.6e8cb","type":"geofence","z":"3f8824be.265114","name":"","mode":"polyline","inside":"true","rad":0,"points":[{"latitude":50.97063938899242,"longitude":-1.366428851033561},{"latitude":50.97063938899242,"longitude":-1.366428851033561},{"latitude":50.964936850828614,"longitude":-1.3668150891317052},{"latitude":50.964936850828614,"longitude":-1.3668150891317052},{"latitude":50.967666589148386,"longitude":-1.3576741208089513},{"latitude":50.967666589148386,"longitude":-1.3576741208089513},{"latitude":50.97074748721977,"longitude":-1.3662142743123695}],"centre":{},"x":520,"y":240,"wires":[["6599a4f8.9d7c74"]]},{"id":"48258625.c00d28","type":"inject","z":"3f8824be.265114","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":160,"y":180,"wires":[["d55d5891.eadfd8"]]},{"id":"d55d5891.eadfd8","type":"function","z":"3f8824be.265114","name":"","func":"msg.location = {};\nmsg.location.lat = 0.0;\nmsg.location.lon = 0.0;\nreturn msg;","outputs":1,"noerr":0,"x":310,"y":180,"wires":[["6e027ecc.6e8cb","2d352799.016928","ed9046b5.2b1cd8"]]}]

**Comment by shaddow825** [comment]
Weird, importing your's works. So I deleted mine and readded it and things seem normal. Wonder whats wrong with the old one.

**Comment by shaddow825** [comment]
Here is a flow over the local downtown area where the map looks identical but the flow shows -456.x degrees longitude. The top node doesn't work but looks correct on the map.

[{"id":"98bc8cdd.c944e8","type":"geofence","z":"8b6e79cf.91c8f","name":"","mode":"polyline","inside":"true","rad":0,"points":[{"latitude":36.14293468772713,"longitude":-95.99149703979492},{"latitude":36.14328124902658,"longitude":-96.00299835205078},{"latitude":36.161464904985436,"longitude":-96.00303053855895},{"latitude":36.161464904985436,"longitude":-95.98002791404723},{"latitude":36.1430040001095,"longitude":-95.97990989685059}],"centre":{},"x":634,"y":509,"wires":[["e8a1a619.a9e8f8"]]},{"id":"e42c31f4.e68f8","type":"function","z":"8b6e79cf.91c8f","name":"","func":"//50.9674878,-1.3621705\nmsg.location = {};\nmsg.location.lat = 35.977079013587364;\nmsg.location.lon = -95.97336341862788;\nreturn msg;","outputs":1,"noerr":0,"x":425,"y":502,"wires":[["98bc8cdd.c944e8","63e89152.b2d66"]]},{"id":"8e2a3d6e.50fbc","type":"inject","z":"8b6e79cf.91c8f","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":"","x":275,"y":502,"wires":[["e42c31f4.e68f8"]]},{"id":"e8a1a619.a9e8f8","type":"debug","z":"8b6e79cf.91c8f","name":"","active":true,"console":"false","complete":"true","x":865,"y":482,"wires":[]},{"id":"63e89152.b2d66","type":"geofence","z":"8b6e79cf.91c8f","name":"Neighborhood","mode":"polyline","inside":"true","rad":0,"points":[{"latitude":36.14291735962196,"longitude":-456.0020327568054},{"latitude":36.16176807456193,"longitude":-456.0020327568054},{"latitude":36.16176807456193,"longitude":-455.9786868095398},{"latitude":36.14291735962196,"longitude":-455.9786868095398}],"centre":{},"x":640,"y":461,"wires":[["e8a1a619.a9e8f8"]]}]

**Comment by shaddow825** [comment]
Here's a flow with my old node and a new node. 

The old one shows -456 longitude but looks right on the map.

[{"id":"98bc8cdd.c944e8","type":"geofence","z":"8b6e79cf.91c8f","name":"","mode":"polyline","inside":"both","rad":0,"points":[{"latitude":36.14293468772713,"longitude":-95.99149703979492},{"latitude":36.14328124902658,"longitude":-96.00299835205078},{"latitude":36.161464904985436,"longitude":-96.00303053855895},{"latitude":36.161464904985436,"longitude":-95.98002791404723},{"latitude":36.1430040001095,"longitude":-95.97990989685059}],"centre":{},"x":634,"y":509,"wires":[["e8a1a619.a9e8f8"]]},{"id":"e42c31f4.e68f8","type":"function","z":"8b6e79cf.91c8f","name":"","func":"//50.9674878,-1.3621705\nmsg.location = {};\nmsg.location.lat = 36.15371264;\nmsg.location.lon = -95.99119659;\nreturn msg;","outputs":1,"noerr":0,"x":425,"y":502,"wires":[["98bc8cdd.c944e8","63e89152.b2d66"]]},{"id":"8e2a3d6e.50fbc","type":"inject","z":"8b6e79cf.91c8f","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":"","x":275,"y":502,"wires":[["e42c31f4.e68f8"]]},{"id":"e8a1a619.a9e8f8","type":"debug","z":"8b6e79cf.91c8f","name":"","active":true,"console":"false","complete":"true","x":865,"y":482,"wires":[]},{"id":"63e89152.b2d66","type":"geofence","z":"8b6e79cf.91c8f","name":"Neighborhood","mode":"polyline","inside":"both","rad":0,"points":[{"latitude":36.14291735962196,"longitude":-456.0020327568054},{"latitude":36.16176807456193,"longitude":-456.0020327568054},{"latitude":36.16176807456193,"longitude":-455.9786868095398},{"latitude":36.14291735962196,"longitude":-455.9786868095398}],"centre":{},"x":640,"y":461,"wires":[["e8a1a619.a9e8f8"]]}]
